name: Deno CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        deno-version: [2.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ matrix.deno-version }}
    
    - name: Verify formatting
      run: deno fmt --check
    
    - name: Run linter
      run: deno lint
    
    - name: Type check
      run: deno task check
    
    - name: Run tests
      run: deno task test
    
    - name: Generate coverage
      run: deno test --allow-read --coverage=coverage src/tests.ts
    
    - name: Generate coverage report
      run: deno coverage coverage --lcov --output=coverage.lcov
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.lcov
        flags: deno-${{ matrix.deno-version }}
        fail_ci_if_error: false