name: Publish to JSR

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: 2.x
    
    - name: Verify formatting
      run: deno fmt --check
    
    - name: Run linter
      run: deno lint
    
    - name: Type check
      run: deno task check
    
    - name: Run tests
      run: deno task test
    
    - name: Publish to JSR
      run: deno publish